steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/hello-world-service:latest', '.']
# - name: "gcr.io/cloud-builders/gcloud"
#   args: ['container', 'images', 'add-tag', 'gcr.io/${PROJECT_ID}/hello-world-service:latest', 'gcr.io/${PROJECT_ID}/hello-world-service:latest-1']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/${PROJECT_ID}/hello-world-service:latest']
options:
  logging: CLOUD_LOGGING_ONLY
