- kind: SpannerDatabase
  name: HelloWorldDatabase
  tables:
    - kind: Table
      name: User
      columns:
        - name: userId
          type: string
        - name: createdTimeMs
          type: float64
      primaryKeys:
        - userId
      insert: InsertUser
      delete: DeleteUser
      get: GetUser
      update: UpdateUser
  outputDdl: ./db/ddl
  outputSql: ./db/sql
